permit nopass noroot cmd /usr/sbin/service args haproxy reload
permit nopass noroot cmd /usr/sbin/service args haproxy restart
permit nopass noroot cmd /usr/sbin/service args haproxy status
permit nopass noroot cmd /usr/sbin/service args haproxy configtest
